# <https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html>
[licenses]
# List of explicitly allowed licenses. I'm open to adding more! This is just the (almost) minimal
# list to satisfy current dependencies, but adding more is certainly an option.
#
# <https://spdx.org/licenses/>
allow = ["MIT", "Apache-2.0", "MPL-2.0", "Unicode-3.0"]

# <https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html>
[advisories]
ignore = [
    # Advisory: `dtolnay/paste` is unmaintained. This is fine to ignore because it's not abandoned,
    # it's just finished:
    #
    # > For my own use cases I would use paste since it is 'finished' and does everything I need.
    #
    # <https://github.com/rustsec/advisory-db/pull/2215#issuecomment-2709315704>
    "RUSTSEC-2024-0436",
]
