# SPDX-License-Identifier: MPL-2.0
#
# Copyright © 2025 RemasteredArch
#
# This Source Code Form is subject to the terms of the Mozilla Public License, version 2.0. If a
# copy of the Mozilla Public License was not distributed with this file, You can obtain one at
# <https://mozilla.org/MPL/2.0/>.

name: General Lints

on: [push, pull_request]

jobs:
    cargo-deps:
        runs-on: ubuntu-24.04
        outputs:
            bin_path: ${{ steps.cargo.outputs.bin_path }}
            versions_hash: ${{ steps.versions.outputs.versions_hash }}
        steps:
            - name: Setup - Check latest versions
              id: versions
              run: |
                latest_crate_version() {
                    local crate="$1"
                    local name="${2:-$crate}"

                    local latest
                    latest="$(
                        curl -fsSL \
                            -H 'User-Agent: sciutil/general.yml (https://github.com/RemasteredArch/sciutil)'\
                            "https://crates.io/api/v1/crates/$crate" \
                            | grep --only-matching '"num": \?"[^"]\+"' \
                            | head -n 1 \
                            | sed 's/"num": \?"\(.*\)"/\1/'
                    )"

                    echo "latest_$name=$latest" >> "$GITHUB_OUTPUT"
                    echo "$latest" >> 'cargo-versions.txt'
                }

                latest_crate_version just
                latest_crate_version typst-cli typst
                latest_crate_version typstyle
                latest_crate_version taplo-cli taplo

                hash="$(sha256sum 'cargo-versions.txt' | grep --only-matching '^[a-zA-Z0-9]\+')"
                echo "versions_hash=$hash" >> "$GITHUB_OUTPUT"
            - id: cargo
              run: |
                bin_path="${CARGO_INSTALL_ROOT:-${CARGO_HOME:-$HOME/.cargo}/bin}"
                echo "bin_path=$bin_path" >> "$GITHUB_OUTPUT"
                echo "$bin_path" >> "$GITHUB_PATH"
            - name: Setup - Cargo binary caches
              uses: actions/cache@v4
              with:
                key: "${{ github.job }}-${{ runner.os }}-${{ runner.arch }}-${{ steps.versions.outputs.versions_hash }}"
                path: ${{ steps.cargo.outputs.bin_path }}
            - name: Setup - Check and install packages
              run: |
                installed_just="$(
                    if command -v just &> /dev/null; then
                        just --version \
                            | grep '^just [0-9.]\+$' \
                            | sed 's/just \(.*\)$/\1/'
                    else
                        echo ''
                    fi
                )"
                latest_just="${{ steps.versions.outputs.latest_just }}"
                echo "Latest version of Just: $latest_just"
                echo "Installed version of Just: $installed_just"

                installed_typst="$(
                    if command -v typst &> /dev/null; then
                        typst --version \
                            | grep '^typst [0-9.]\+ ([0-9 a-z]\+)$' \
                            | sed 's/typst \(.*\) ([0-9 a-z]\+)$/\1/'
                    else
                        echo ''
                    fi
                )"
                latest_typst="${{ steps.versions.outputs.latest_typst }}"
                echo "Latest version of Typst: $latest_typst"
                echo "Installed version of Typst: $installed_typst"

                installed_typstyle="$(
                    if command -v typstyle &> /dev/null; then
                        typstyle --version \
                            | grep '^Version: \+[0-9.]\+$' \
                            | sed 's/^Version: \+\(.*\)$/\1/'
                    else
                        echo ''
                    fi
                )"
                latest_typstyle="${{ steps.versions.outputs.latest_typstyle }}"
                echo "Latest version of typstyle: $latest_typstyle"
                echo "Installed version of typstyle: $installed_typstyle"

                installed_taplo="$(
                    if command -v taplo &> /dev/null; then
                        taplo --version \
                            | grep '^taplo [0-9.]\+$' \
                            | sed 's/taplo \(.*\)$/\1/'
                    else
                        echo ''
                    fi
                )"
                latest_taplo="${{ steps.versions.outputs.latest_taplo }}"
                echo "Latest version of taplo: $latest_taplo"
                echo "Installed version of taplo: $installed_taplo"

                old_packages=''
                [ "$latest_just" = "$installed_just" ] || old_packages='just'
                [ "$latest_typst" = "$installed_typst" ] || old_packages="$old_packages typst-cli"
                [ "$latest_typstyle" = "$installed_typstyle" ] || old_packages="$old_packages typstyle"
                [ "$latest_taplo" = "$installed_taplo" ] || old_packages="$old_packages taplo-cli"

                [ "$old_packages" = '' ] && {
                    echo 'All packages already up to date!'
                    exit 0
                }

                echo 'Installing cargo'

                # Assume that the Cargo version in the 24.04 container is new enough.
                #
                # I'm purposefully using `cargo --version` instead of `command -v cargo` because
                # this will catch the Cargo binaries from the cache that will be unhappy about not
                # having the rest of the toolchain.
                if cargo --version &> /dev/null; then
                    echo 'Cargo is already installed!'
                else
                  # TODO: this could probably be a minimal version
                  curl --proto '=https' --tlsv1.2 -sSf 'https://sh.rustup.rs' | sh -s -- -y
                  # shellcheck disable=SC1091
                  . "$HOME/.cargo/env"
                fi

                echo 'Installing packages'
                # I'm purposefully letting it split on spaces.
                #
                # shellcheck disable=SC2086
                cargo install $old_packages

    toml:
        runs-on: ubuntu-24.04
        needs: cargo-deps
        steps:
            # Failing because the taplo image doesn't have Node in `$PATH`.
            - name: Setup - Cargo binary caches
              uses: actions/cache/restore@v4
              with:
                key: "cargo-deps-${{ runner.os }}-${{ runner.arch }}-${{ needs.cargo-deps.outputs.versions_hash }}"
                path: ${{ needs.cargo-deps.outputs.bin_path }}
                fail-on-cache-miss: true
            - run: echo "${{ needs.cargo-deps.outputs.bin_path }}" >> "$GITHUB_PATH"
            - uses: actions/checkout@v4
            - name: Action - Check TOML
              run: just ci-toml

    yaml:
        runs-on: ubuntu-24.04
        needs: cargo-deps
        steps:
            - name: Setup - Cargo binary caches
              uses: actions/cache/restore@v4
              with:
                key: "cargo-deps-${{ runner.os }}-${{ runner.arch }}-${{ needs.cargo-deps.outputs.versions_hash }}"
                path: ${{ needs.cargo-deps.outputs.bin_path }}
                fail-on-cache-miss: true
            - run: echo "${{ needs.cargo-deps.outputs.bin_path }}" >> "$GITHUB_PATH"
            - uses: actions/checkout@v4
            - name: Setup - Install go
              uses: actions/setup-go@v5
              with:
                go-version: '1'
                check-latest: true
            - name: Setup - Resolve package info
              id: goenv
              env:
                PACKAGES: |
                    yamlfmt:github.com/google/yamlfmt:v0.16
                    actionlint:github.com/rhysd/actionlint:v1
                HASH_LEN_TARGET: '64'
                MIN_HASH_LEN: '16'
              run: |
                output() {
                    local key_or_pair="$1"

                    # Avoids `set -u` errors.
                    local value="${2:-}"

                    local delimeter="${3:-EOF}"

                    local output
                    output="$(
                        if [ -z "$value" ]; then
                            # Single line output, `key_or_pair` is a key/value pair.
                            echo "$key_or_pair"
                        else
                            # Multiline output, `key_or_pair` is just a key.
                            echo "$key_or_pair<<$delimeter"
                            echo "$value"
                            echo "$delimeter"
                        fi
                    )"

                    echo "$output" >&2
                    echo "$output" >> "$GITHUB_OUTPUT"
                }

                resolve_package() {
                    local package_bin
                    package_bin="$1"

                    local package_path
                    package_path="$2"

                    # Assumes `vMAJOR.MINOR`, `vMAJOR.MINOR`, or `vMAJOR.MINOR.PATCH`, not full
                    # SemVer.
                    local package_semver
                    package_semver="$3"

                    download() {
                        local url
                        url="$1"

                        if [ "$(type curl 2> /dev/null)" ]; then
                            curl --fail --silent --show-error --location "$url"
                            return
                        fi

                        if [ "$(type wget 2> /dev/null)" ]; then
                            wget -qO - "$url"
                            return
                        fi

                        echo "Both 'wget' and 'curl' are unavailable!" >&2
                        return 1
                    }

                    local api_base
                    api_base=''
                    while read -r proxy; do
                        if [ "$proxy" = 'direct' ] || [ "$proxy" = 'off' ] || [ -z "$proxy" ]; then
                            continue
                        fi

                        # E.g., `https://proxy.golang.org/github.com/google/yamlfmt/@v`.
                        api_base="$proxy/$package_path/@v"
                        break
                    done < <(go env GOPROXY | tr ',|' '\n')

                    # E.g.,
                    #
                    # ```text
                    # v0.2.0
                    # v0.1.0
                    # v0.3.0
                    # v0.1.1
                    # ```
                    local versions
                    versions="$(download "$api_base/list")"

                    # E.g., `v0.1.1` for some `PACKAGE_SEMVER='v0.1'`.
                    local version
                    version="$(
                        echo "$versions" | grep "^$package_semver.*" | sort -rV | head -n 1
                    )"

                    # TODO: Parse for other forms than `sum.golang.org`.
                    local gosumdb
                    gosumdb="https://$(go env GOSUMDB)"

                    local hash
                    hash="$(
                        download "$gosumdb/lookup/$package_path@$version" |
                            grep "^$package_path $version/go.mod h1:" |
                            sed 's/^.* h1:\(.*\)$/\1/'
                    )"

                    # E.g., `YAMLFMT`.
                    local package_bin_upper
                    package_bin_upper="$(echo "$package_bin" | tr '[:lower:]' '[:upper:]')"

                    output "${package_bin_upper}_GOMOD_SHA256=$hash"
                    output "${package_bin_upper}_VERSION=$version"

                    printf '%s\n%s\n' "$version" "$hash"
                }

                get_column() {
                    local line
                    line="$1"

                    local column
                    column="$2"

                    echo "$line" | awk -F ':' "{ print \$$column }"
                }

                trim_whitespace() {
                    # E.g., `  foobar  `.
                    local input="$1"

                    # E.g., `foobar  `.
                    local trimmed
                    trimmed="${input#"${input%%[![:space:]]*}"}"

                    # E.g., `foobar`.
                    trimmed="${trimmed%"${trimmed##*[![:space:]]}"}"

                    echo "$trimmed"
                }

                PACKAGES="$(trim_whitespace "$PACKAGES")"

                package_count="$(echo "$PACKAGES" | wc -l)"
                hash_len="$(( HASH_LEN_TARGET / package_count ))"
                hash_len="$(( hash_len > MIN_HASH_LEN ? hash_len : MIN_HASH_LEN ))"

                exact_packages=''
                cumulative_hash=''
                while read -r package; do
                    if [ -z "$package" ]; then
                        continue
                    fi

                    package_bin="$(get_column "$package" 1)"
                    package_path="$(get_column "$package" 2)"
                    package_semver="$(get_column "$package" 3)"

                    {
                        read -r version
                        read -r hash
                    } < <(resolve_package "$package_bin" "$package_path" "$package_semver")

                    # Previously I used `expr substr "$hash" 1 "$hash_len"`, but that is not POSIX.
                    # `cut` operates per line, but I am certain that there will only ever be one
                    # line, so it is equivalent.
                    hash="$(echo "$hash" | cut -c "-$hash_len")"

                    cumulative_hash="$cumulative_hash$hash"
                    exact_packages="$(
                        printf '%s\n%s' "$exact_packages" "$package_bin:$package_path:$version"
                    )"
                done < <(echo "$PACKAGES")

                output "CUMULATIVE_GOMOD_SHA256=$cumulative_hash"
                output "PACKAGES" "$exact_packages"

                for var in GOCACHE GOMODCACHE GOVERSION; do
                    output "$var=$(go env $var)"
                done
            - name: Setup - Go caches
              uses: actions/cache@v4
              with:
                # This is longer than 100 characters, but `yamlfmt` won't let me format it nicer :(
                key: "${{ github.job }}-${{ runner.os }}-${{ runner.arch }}-${{ steps.goenv.outputs.GOVERSION }}-${{ steps.goenv.outputs.CUMULATIVE_GOMOD_SHA256 }}"
                path: |
                    ${{ steps.goenv.outputs.GOCACHE }}
                    ${{ steps.goenv.outputs.GOMODCACHE }}
            - name: Setup - Install packages
              run: |
                start_group() {
                    local title="$1"
                    echo "::group::$title"
                }

                end_group() {
                    echo '::endgroup::'
                }

                get_column() {
                    local line
                    line="$1"

                    local column
                    column="$2"

                    echo "$line" | awk -F ':' "{ print \$$column }"
                }

                while read -r package; do
                    if [ -z "$package" ]; then
                        continue
                    fi

                    package_bin="$(get_column "$package" 1)"
                    package_path="$(get_column "$package" 2)"
                    package_version="$(get_column "$package" 3)"

                    start_group "Installing $package_bin $package_version"

                    go install "$package_path/cmd/$package_bin@$package_version"

                    end_group
                done < <(echo "${{ steps.goenv.outputs.PACKAGES }}" )

            - name: Action - Check YAML and GitHub Actions workflows
              run: just ci-yaml

    markdown:
        runs-on: ubuntu-24.04
        needs: cargo-deps
        steps:
            - name: Setup - Cargo binary caches
              uses: actions/cache/restore@v4
              with:
                key: "cargo-deps-${{ runner.os }}-${{ runner.arch }}-${{ needs.cargo-deps.outputs.versions_hash }}"
                path: ${{ needs.cargo-deps.outputs.bin_path }}
                fail-on-cache-miss: true
            - run: echo "${{ needs.cargo-deps.outputs.bin_path }}" >> "$GITHUB_PATH"
            - uses: actions/checkout@v4
            - name: Setup - Install mdformat
              run: |
                pipx install mdformat~=0.7
                echo "${PIPX_BIN_DIR:-$HOME/.local/bin}" >> "$GITHUB_PATH"
            - name: Action - Check Markdown file
              run: just ci-markdown

    typst:
        runs-on: ubuntu-24.04
        needs: cargo-deps
        steps:
            - uses: actions/checkout@v4
            - name: Setup - Cargo binary caches
              uses: actions/cache/restore@v4
              with:
                key: "cargo-deps-${{ runner.os }}-${{ runner.arch }}-${{ needs.cargo-deps.outputs.versions_hash }}"
                path: ${{ needs.cargo-deps.outputs.bin_path }}
                fail-on-cache-miss: true
            - run: echo "${{ needs.cargo-deps.outputs.bin_path }}" >> "$GITHUB_PATH"
            - name: Action - Check Typst documents
              run: just ci-typst
